"""v0.3.3

Revision ID: 1cd085d06c56
Revises: b31c01e30830
Create Date: 2025-11-12 15:38:07.193381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd085d06c56'
down_revision: Union[str, Sequence[str], None] = 'b31c01e30830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_core_phone_number'), 'user_core', ['phone_number'], unique=True)
    op.create_index(op.f('ix_user_telegram_tel_chat_id'), 'user_telegram', ['tel_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_tel_chat_id'), table_name='user_telegram')
    op.drop_index(op.f('ix_user_core_phone_number'), table_name='user_core')
    # ### end Alembic commands ###
