"""v0.6.8

Revision ID: 31613b15a002
Revises: 6f6248bc69f9
Create Date: 2025-11-16 15:11:50.830470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31613b15a002'
down_revision: Union[str, Sequence[str], None] = '6f6248bc69f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_recharge_invoices', sa.Column('get_config', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_recharge_invoices', 'get_config')
    # ### end Alembic commands ###
