"""v0.4.3

Revision ID: 43ee57b3af39
Revises: 1cd085d06c56
Create Date: 2025-11-13 12:44:07.759837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ee57b3af39'
down_revision: Union[str, Sequence[str], None] = '1cd085d06c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_core', sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_core', 'create_dt')
    # ### end Alembic commands ###
