"""final models

Revision ID: 4889a9afa98c
Revises: 
Create Date: 2025-12-09 00:53:24.508919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4889a9afa98c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_core',
    sa.Column('upstream_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tel_user_id', sa.String(length=128), nullable=True),
    sa.Column('tel_chat_id', sa.String(length=128), nullable=True),
    sa.Column('unique_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_repres', sa.Boolean(), nullable=True),
    sa.Column('wallet_balance', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('wallet_balance >= 0', name='ck_user_wallet_non_negative'),
    sa.ForeignKeyConstraint(['upstream_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_core_unique_id'), 'user_core', ['unique_id'], unique=True)
    op.create_table('configuration_invoices',
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('base_price', sa.BigInteger(), nullable=True),
    sa.Column('discount_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=True),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user_core.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_panel_core',
    sa.Column('user_core', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url_address', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('max_volume', sa.Integer(), nullable=True),
    sa.Column('used_volume', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_core'], ['user_core.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_panel_core_user_core'), 'configuration_panel_core', ['user_core'], unique=False)
    op.create_table('configurations',
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('total_volume_gb', sa.BigInteger(), nullable=True),
    sa.Column('volume_ceiling_gb', sa.BigInteger(), nullable=True),
    sa.Column('consumed_volume_gb', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('consumed_volume_gb <= volume_ceiling_gb', name='ck_conf_consumed_le_ceiling'),
    sa.CheckConstraint('volume_ceiling_gb <= total_volume_gb', name='ck_conf_ceiling_le_total'),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user_core.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('percent', sa.SmallInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('expired_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_ceiling', sa.Integer(), nullable=True),
    sa.Column('maximum_discount_amount', sa.BigInteger(), nullable=True),
    sa.Column('minimum_purchase_amount', sa.BigInteger(), nullable=True),
    sa.Column('number_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('refund', sa.Boolean(), nullable=True),
    sa.Column('synchronicity', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('maximum_discount_amount <= minimum_purchase_amount', name='ck_discount_max_le_min'),
    sa.CheckConstraint('percent >= 0 AND percent <= 100', name='ck_discount_percent_range'),
    sa.CheckConstraint('usage_ceiling >= 0', name='ck_discount_usage_ceiling'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('representatives_core',
    sa.Column('user_core', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('otp_code', sa.String(length=255), nullable=True),
    sa.Column('otp_exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tel_bot_token', sa.String(length=128), nullable=True),
    sa.Column('tel_channel_id', sa.String(length=128), nullable=True),
    sa.Column('tel_support_id', sa.String(length=128), nullable=True),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('base_selling_price', sa.BigInteger(), nullable=False),
    sa.Column('base_purchase_price', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('base_purchase_price >= 0', name='ck_rep_purchase_price_non_negative'),
    sa.CheckConstraint('base_selling_price > 0', name='ck_rep_selling_price_positive'),
    sa.ForeignKeyConstraint(['user_core'], ['user_core.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_representatives_core_user_core'), 'representatives_core', ['user_core'], unique=True)
    op.create_table('wallet_recharge_invoices',
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('charge_amount', sa.BigInteger(), nullable=True),
    sa.Column('get_config', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.Enum('PRE_FACTURE', 'WAITING', 'CONFIRMED', 'REJECTED', 'PAY_WALLET', 'CONFIGURATION_DIRECTE', name='walletinvoicestatuschoices'), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user_core.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_discount',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('count_uses', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.Enum('USED_BY_USERS', 'AUTHORIZED_USERS_FOR_USE', name='userdiscounttype_choices'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_discount')
    op.drop_table('wallet_recharge_invoices')
    op.drop_index(op.f('ix_representatives_core_user_core'), table_name='representatives_core')
    op.drop_table('representatives_core')
    op.drop_table('discount')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_configuration_panel_core_user_core'), table_name='configuration_panel_core')
    op.drop_table('configuration_panel_core')
    op.drop_table('configuration_invoices')
    op.drop_index(op.f('ix_user_core_unique_id'), table_name='user_core')
    op.drop_table('user_core')
    # ### end Alembic commands ###
