"""v0.5.7

Revision ID: 5b768e9944d1
Revises: ed3630ddb232
Create Date: 2025-11-14 22:52:21.956462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b768e9944d1'
down_revision: Union[str, Sequence[str], None] = 'ed3630ddb232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration_invoices', 'expiration_at')
    op.drop_column('wallet_recharge_invoices', 'expiration_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_recharge_invoices', sa.Column('expiration_at', sa.DATETIME(), nullable=True))
    op.add_column('configuration_invoices', sa.Column('expiration_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
