"""V0.0.0

Revision ID: 5f6de3358c91
Revises: 4889a9afa98c
Create Date: 2025-12-11 15:46:09.883600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6de3358c91'
down_revision: Union[str, Sequence[str], None] = '4889a9afa98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_column('discount', 'volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('volume', sa.BIGINT(), nullable=True))
    op.drop_column('configurations', 'name')
    # ### end Alembic commands ###
