"""v0.3.1

Revision ID: 6a3698806abc
Revises: c0fc889b8426
Create Date: 2025-11-12 14:22:23.857190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3698806abc'
down_revision: Union[str, Sequence[str], None] = 'c0fc889b8426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('otp_code', sa.String(length=5), nullable=True))
    op.add_column('user_auth', sa.Column('otp_exp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'otp_exp')
    op.drop_column('user_auth', 'otp_code')
    # ### end Alembic commands ###
