"""v0.2.1

Revision ID: c0fc889b8426
Revises: d2997a520dcc
Create Date: 2025-11-12 13:20:28.168014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc889b8426'
down_revision: Union[str, Sequence[str], None] = 'd2997a520dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('user_core', 'national_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_core', sa.Column('national_code', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('user_auth', 'password_changed_at')
    # ### end Alembic commands ###
