"""v0.1.0

Revision ID: d2997a520dcc
Revises: 5a5a530e6069
Create Date: 2025-11-12 12:08:44.893865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2997a520dcc'
down_revision: Union[str, Sequence[str], None] = '5a5a530e6069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user_finance', sa.Column('card_number', sa.String(length=16), nullable=True))
    op.add_column('user_finance', sa.Column('base_selling_price', sa.String(length=16), nullable=True))
    op.add_column('user_finance', sa.Column('base_purchase_price', sa.String(length=16), nullable=True))
    op.drop_column('user_finance', 'base_price')
    op.add_column('user_telegram', sa.Column('tel_support_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_telegram', 'tel_support_id')
    op.add_column('user_finance', sa.Column('base_price', sa.VARCHAR(length=16), nullable=True))
    op.drop_column('user_finance', 'base_purchase_price')
    op.drop_column('user_finance', 'base_selling_price')
    op.drop_column('user_finance', 'card_number')
    op.drop_column('user_auth', 'is_admin')
    # ### end Alembic commands ###
