"""v0.5.6

Revision ID: ed3630ddb232
Revises: 3f96bfebbaab
Create Date: 2025-11-14 17:29:07.952776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3630ddb232'
down_revision: Union[str, Sequence[str], None] = '3f96bfebbaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_invoices',
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expiration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_price', sa.String(length=16), nullable=True),
    sa.Column('discount_amount', sa.String(length=16), nullable=True),
    sa.Column('total_price', sa.String(length=16), nullable=True),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user_core.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_recharge_invoices',
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('charge_amount', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expiration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'CONFIRMED', 'REJECTED', name='invoicestatus_choices'), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user_core.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchase_invoices')
    op.drop_column('user_finance', 'total_volume')
    op.drop_column('user_finance', 'sales_volume_ceiling')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_finance', sa.Column('sales_volume_ceiling', sa.INTEGER(), nullable=True))
    op.add_column('user_finance', sa.Column('total_volume', sa.VARCHAR(length=16), nullable=True))
    op.create_table('purchase_invoices',
    sa.Column('buyer_user_id', sa.INTEGER(), nullable=True),
    sa.Column('seller_user_id', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.VARCHAR(length=16), nullable=True),
    sa.Column('create_dt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expiration_dt', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('base_price', sa.VARCHAR(length=16), nullable=True),
    sa.Column('discount_amount', sa.VARCHAR(length=16), nullable=True),
    sa.Column('total_price', sa.VARCHAR(length=16), nullable=True),
    sa.Column('descriptions', sa.VARCHAR(), nullable=True),
    sa.Column('config_output', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user_core.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wallet_recharge_invoices')
    op.drop_table('configuration_invoices')
    # ### end Alembic commands ###
